### ISSUE TITLE
Only shows for a split second, then closes.

### ISSUE THREAD

**Issue by qrwtey** [Om-Thorat/Term-Spotify#2] opened 2023-07-28 21:27 UTC
After moving the repo to a folder and installing the dependencies, I started Spotify with the PlayBackApi from the marketplace installed and then ran app.py
The window flashes for a split second and then closes on itself. I just barely notice the SpotiUi elements. 
I also tried to place PlayBackApi in the spicetify extension folder, it didn't work either.
Any ideas?

**Comment by Om-Thorat** [comment] 2023-07-29 05:26
Oh that's weird!

Can you check the console for Spotify with devtools? You can do that by `spicetify enable-devtools` and then `ctrl+shift+i`
send me a screenshot 👀 also try opening app.py while the console is open and tell me if you see any logs!

**Comment by qrwtey** [comment] 2023-07-29 12:28
**To the left:** my attempts to install. Connection refused and no connection at localhost:443.
**To the right:** A new thing I tried is to make app.py wait for input so I can catch these errors (but maybe those two errors are from waiting on input). 
I don't know python so I don't know if I should run scripts with python from the right-click "open with..." drop-down menu.
![image](https://github.com/Om-Thorat/Term-Spotify/assets/62503966/f53087a0-3b3b-4ff6-875f-e9086f99ea55)

**Comment by qrwtey** [comment] 2023-07-29 12:30
localhost works fine when I'm making live servers for web dev stuff with VS Code
Windows 10 64bit
Python 3.10, 3.11
``` 
PS C:\Users\name\Documents\Program Files\GitHub\Misc\Term-Spotify> pip install -r requirements.txt
Requirement already satisfied: flask in c:\users\name\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r requirements.txt (line 1)) (2.3.2)
Requirement already satisfied: textual in c:\users\name\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from -r requirements.txt (line 2)) (0.30.0)
Requirement already satisfied: Werkzeug>=2.3.3 in c:\users\name\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from flask->-r requirements.txt (line 1)) (2.3.6)
Requirement already satisfied: Jinja2>=3.1.2 in c:\users\name\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from flask->-r requirements.txt (line 1)) (3.1.2)
Requirement already satisfied: itsdangerous>=2.1.2 in c:\users\name\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from flask->-r requirements.txt (line 1)) (2.1.2)
Requirement already satisfied: click>=8.1.3 in c:\users\name\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from flask->-r requirements.txt (line 1)) (8.1.6)
Requirement already satisfied: blinker>=1.6.2 in c:\users\name\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from flask->-r requirements.txt (line 1)) (1.6.2)
Requirement already satisfied: importlib-metadata>=4.11.3 in c:\users\name\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from textual->-r requirements.txt (line 2)) (6.8.0)
Requirement already satisfied: markdown-it-py[linkify,plugins]>=2.1.0 in c:\users\name\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from textual->-r requirements.txt (line 2)) (3.0.0)
Requirement already satisfied: rich>=13.3.3 in c:\users\name\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from textual->-r requirements.txt (line 2)) (13.4.2)
Requirement already satisfied: typing-extensions<5.0.0,>=4.4.0 in c:\users\name\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from textual->-r requirements.txt (line 2)) (4.7.1)
Requirement already satisfied: colorama in c:\users\name\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from click>=8.1.3->flask->-r requirements.txt (line 1)) (0.4.6)
Requirement already satisfied: zipp>=0.5 in c:\users\name\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from importlib-metadata>=4.11.3->textual->-r requirements.txt (line 2)) (3.16.2)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\name\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from Jinja2>=3.1.2->flask->-r requirements.txt (line 1)) (2.1.3)
Requirement already satisfied: mdurl~=0.1 in c:\users\name\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from markdown-it-py[linkify,plugins]>=2.1.0->textual->-r requirements.txt (line 2)) (0.1.2)
Requirement already satisfied: linkify-it-py<3,>=1 in c:\users\name\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from markdown-it-py[linkify,plugins]>=2.1.0->textual->-r requirements.txt (line 2)) (2.0.2)
Requirement already satisfied: mdit-py-plugins in c:\users\name\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from markdown-it-py[linkify,plugins]>=2.1.0->textual->-r requirements.txt (line 2)) (0.4.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\name\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from rich>=13.3.3->textual->-r requirements.txt (line 2)) (2.15.1)
Requirement already satisfied: uc-micro-py in c:\users\name\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from linkify-it-py<3,>=1->markdown-it-py[linkify,plugins]>=2.1.0->textual->-r requirements.txt (line 2)) (1.0.2)
PS C:\Users\name\Documents\Program Files\GitHub\Misc\Term-Spotify>
```

**Comment by Om-Thorat** [comment] 2023-07-29 13:47
> To the left: my attempts to install. Connection refused and no connection at localhost:443.
To the right: A new thing I tried is to make app.py wait for input so I can catch these errors (but maybe those two errors are from waiting on input).
I don't know python so I don't know if I should run scripts with python from the right-click "open with..." drop-down menu.

Your extension seems to be working fine it keeps on looking for localhost:443 connection on a websocket it gives an error until you start the app which is the host and connects to it on localhost:443.

Can you remove your edits to the python scripts and instead try running them from your powershell by `python3 app.py` or `py app.py`, 

Thank you!

**Comment by qrwtey** [comment] 2023-07-29 14:54
removed my input('Wait') edit and ran with powershell:
```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\name\Documents\Program Files\GitHub\Misc\Term-Spotify> py app.py
Traceback (most recent call last):
  File "C:\Users\name\Documents\Program Files\GitHub\Misc\Term-Spotify\app.py", line 2, in <module>
    from textual.reactive import reactive
ModuleNotFoundError: No module named 'textual'
PS C:\Users\name\Documents\Program Files\GitHub\Misc\Term-Spotify> python3 app.py
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────
│ C:\Users\name\Documents\Program Files\GitHub\Misc\Term-Spotify\app.py:17 in update_song
│
│   14 │   │   self.set_interval(1 / 60, self.update_song)
│   15 │
│   16 │   def update_song(self):
│ ❱ 17 │   │   self.song = pl.getdata()
│   18 │
│   19 │   def watch_song(self):
│   20 │   │   self.update(f"Now Playing {self.song}")
│
│ ╭──────────── locals ────────────╮
│ │ self = nowplaying(id='status') │
│ ╰────────────────────────────────╯
│
│ C:\Users\name\Documents\Program Files\GitHub\Misc\Term-Spotify\api.py:38 in getdata
│
│   35 │
│   36 │   def getdata(self):
│   37 │   │   self.proc.stdin.write("getdata\n")
│ ❱ 38 │   │   self.proc.stdin.flush()
│   39 │   │   return self.proc.stdout.readline()
│   40
│   41 if __name__ == "__main__":
│
│ ╭───────────────────── locals ─────────────────────╮
│ │ self = <api.Player object at 0x000001C9EA29FC10> │
│ ╰──────────────────────────────────────────────────╯
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
OSError: [Errno 22] Invalid argument

NOTE: 1 of 2 errors shown. Run with --dev to see all errors.
PS C:\Users\name\Documents\Program Files\GitHub\Misc\Term-Spotify>
```

**Comment by Om-Thorat** [comment] 2023-07-29 15:11
weirdly it seems like you don't have the modules installed, try running `pip install textual`

**Comment by qrwtey** [comment] 2023-07-29 16:23
```Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\name\Documents\Program Files\GitHub\Misc\Term-Spotify> pip install textual
Requirement already satisfied: textual in c:\users\name\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (0.30.0)
Requirement already satisfied: importlib-metadata>=4.11.3 in c:\users\name\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from textual) (6.8.0)
Requirement already satisfied: markdown-it-py[linkify,plugins]>=2.1.0 in c:\users\name\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from textual) (3.0.0)
Requirement already satisfied: rich>=13.3.3 in c:\users\name\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from textual) (13.4.2)
Requirement already satisfied: typing-extensions<5.0.0,>=4.4.0 in c:\users\name\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from textual) (4.7.1)
Requirement already satisfied: zipp>=0.5 in c:\users\name\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from importlib-metadata>=4.11.3->textual) (3.16.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\name\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from markdown-it-py[linkify,plugins]>=2.1.0->textual) (0.1.2)
Requirement already satisfied: mdit-py-plugins in c:\users\name\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from markdown-it-py[linkify,plugins]>=2.1.0->textual) (0.4.0)
Requirement already satisfied: linkify-it-py<3,>=1 in c:\users\name\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from markdown-it-py[linkify,plugins]>=2.1.0->textual) (2.0.2)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\name\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from rich>=13.3.3->textual) (2.15.1)
Requirement already satisfied: uc-micro-py in c:\users\name\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from linkify-it-py<3,>=1->markdown-it-py[linkify,plugins]>=2.1.0->textual) (1.0.2)
PS C:\Users\name\Documents\Program Files\GitHub\Misc\Term-Spotify>

PS C:\Users\name\Documents\Program Files\GitHub\Misc\Term-Spotify> pip uninstall textual
Found existing installation: textual 0.30.0
Uninstalling textual-0.30.0:
  Would remove:
    c:\users\name\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages\textual-0.30.0.dist-info\*
    c:\users\name\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages\textual\*
Proceed (Y/n)? Y
  Successfully uninstalled textual-0.30.0
  
PS C:\Users\name\Documents\Program Files\GitHub\Misc\Term-Spotify> pip install textual
Collecting textual
  Obtaining dependency information for textual from https://files.pythonhosted.org/packages/a9/a3/c39654e9fa0b8d3e34c7b7fe0dd97bfeae14dbf930cf960afdfdb2c4a1bb/textual-0.30.0-py3-none-any.whl.metadata
  Downloading textual-0.30.0-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: importlib-metadata>=4.11.3 in c:\users\name\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from textual) (6.8.0)
Requirement already satisfied: markdown-it-py[linkify,plugins]>=2.1.0 in c:\users\name\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from textual) (3.0.0)
Requirement already satisfied: rich>=13.3.3 in c:\users\name\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from textual) (13.4.2)
Requirement already satisfied: typing-extensions<5.0.0,>=4.4.0 in c:\users\name\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from textual) (4.7.1)
Requirement already satisfied: zipp>=0.5 in c:\users\name\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from importlib-metadata>=4.11.3->textual) (3.16.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\name\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from markdown-it-py[linkify,plugins]>=2.1.0->textual) (0.1.2)
Requirement already satisfied: linkify-it-py<3,>=1 in c:\users\name\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from markdown-it-py[linkify,plugins]>=2.1.0->textual) (2.0.2)
Requirement already satisfied: mdit-py-plugins in c:\users\name\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from markdown-it-py[linkify,plugins]>=2.1.0->textual) (0.4.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\name\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from rich>=13.3.3->textual) (2.15.1)
Requirement already satisfied: uc-micro-py in c:\users\name\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from linkify-it-py<3,>=1->markdown-it-py[linkify,plugins]>=2.1.0->textual) (1.0.2)
Using cached textual-0.30.0-py3-none-any.whl (395 kB)
Installing collected packages: textual
Successfully installed textual-0.30.0
PS C:\Users\name\Documents\Program Files\GitHub\Misc\Term-Spotify>
```
![image](https://github.com/Om-Thorat/Term-Spotify/assets/62503966/1236b696-4d9d-49df-b877-508c40a240cd)

with "py app.py" it still says "no module named textual", and with "python3 app.py" the same 2 errors still appear in the console when running "python3 app.py"

The only thing I could find about this issue is here: https://github.com/Textualize/textual/issues/71#issuecomment-910082252
That was in 2021, textual should be compatible with Windows by now but are you running something different than Windows? maybe I need to install it differently.

**Comment by Om-Thorat** [comment] 2023-07-29 16:27
nope i am running windows 11, This is crazy what are the errors with python3 app.py ?

do you have a discord? You can contact me on there for more fluid conversations if you wish!

**Comment by qrwtey** [comment] 2023-07-29 16:29
```Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\name\Documents\Program Files\GitHub\Misc\Term-Spotify> python3 app.py
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────
│ C:\Users\name\Documents\Program Files\GitHub\Misc\Term-Spotify\app.py:17 in update_song
│
│   14 │   │   self.set_interval(1 / 60, self.update_song)
│   15 │
│   16 │   def update_song(self):
│ ❱ 17 │   │   self.song = pl.getdata()
│   18 │
│   19 │   def watch_song(self):
│   20 │   │   self.update(f"Now Playing {self.song}")
│
│ ╭──────────── locals ────────────╮
│ │ self = nowplaying(id='status') │
│ ╰────────────────────────────────╯
│
│ C:\Users\name\Documents\Program Files\GitHub\Misc\Term-Spotify\api.py:38 in getdata
│
│   35 │
│   36 │   def getdata(self):
│   37 │   │   self.proc.stdin.write("getdata\n")
│ ❱ 38 │   │   self.proc.stdin.flush()
│   39 │   │   return self.proc.stdout.readline()
│   40
│   41 if __name__ == "__main__":
│
│ ╭───────────────────── locals ─────────────────────╮
│ │ self = <api.Player object at 0x000001777B29FC10> │
│ ╰──────────────────────────────────────────────────╯
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
OSError: [Errno 22] Invalid argument

NOTE: 1 of 3 errors shown. Run with --dev to see all errors.
PS C:\Users\name\Documents\Program Files\GitHub\Misc\Term-Spotify>
```
(I don't know how to use --dev)
edit: there are three errors now? Let me reboot the computer...

**Comment by qrwtey** [comment] 2023-07-29 16:34
```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\name\Documents\Program Files\GitHub\Misc\Term-Spotify> python3 app.py
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────
│ C:\Users\name\Documents\Program Files\GitHub\Misc\Term-Spotify\app.py:17 in update_song
│
│   14 │   │   self.set_interval(1 / 60, self.update_song)
│   15 │
│   16 │   def update_song(self):
│ ❱ 17 │   │   self.song = pl.getdata()
│   18 │
│   19 │   def watch_song(self):
│   20 │   │   self.update(f"Now Playing {self.song}")
│
│ ╭──────────── locals ────────────╮
│ │ self = nowplaying(id='status') │
│ ╰────────────────────────────────╯
│
│ C:\Users\name\Documents\Program Files\GitHub\Misc\Term-Spotify\api.py:38 in getdata
│
│   35 │
│   36 │   def getdata(self):
│   37 │   │   self.proc.stdin.write("getdata\n")
│ ❱ 38 │   │   self.proc.stdin.flush()
│   39 │   │   return self.proc.stdout.readline()
│   40
│   41 if __name__ == "__main__":
│
│ ╭───────────────────── locals ─────────────────────╮
│ │ self = <api.Player object at 0x000001D6C569FC10> │
│ ╰──────────────────────────────────────────────────╯
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
OSError: [Errno 22] Invalid argument

NOTE: 1 of 2 errors shown. Run with --dev to see all errors.
PS C:\Users\name\Documents\Program Files\GitHub\Misc\Term-Spotify>
```

**Comment by Om-Thorat** [comment] 2023-07-29 16:36
okay sorry you have to do this but let's get to the bottom of this can you try running the server.py instead?

* run server.py
* open spotify

**Comment by qrwtey** [comment] 2023-07-29 16:41
```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\name\Documents\Program Files\GitHub\Misc\Term-Spotify> run server.py
run : The term 'run' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ run server.py
+ ~~~
    + CategoryInfo          : ObjectNotFound: (run:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\name\Documents\Program Files\GitHub\Misc\Term-Spotify>
```

**Comment by Om-Thorat** [comment] 2023-07-29 16:42
no no no i meant run as in `py server.py` or `python3 server.py` sorry 😅

**Comment by qrwtey** [comment] 2023-07-29 16:42
My bad:
```
PS C:\Users\name\Documents\Program Files\GitHub\Misc\Term-Spotify> python3 server.py
Traceback (most recent call last):
  File "C:\Users\name\Documents\Program Files\GitHub\Misc\Term-Spotify\server.py", line 2, in <module>
    from flask_socketio import SocketIO
ModuleNotFoundError: No module named 'flask_socketio'
PS C:\Users\name\Documents\Program Files\GitHub\Misc\Term-Spotify>

```

**Comment by Om-Thorat** [comment] 2023-07-29 16:45
it is weird all of these were in the requirements which you have installed but anyway try `pip install flask_socketio`

**Comment by qrwtey** [comment] 2023-07-29 16:46
```
PS C:\Users\name\Documents\Program Files\GitHub\Misc\Term-Spotify> python3 server.py
WebSocket transport not available. Install simple-websocket for improved performance.
 * Serving Flask app 'server'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:443
Press CTRL+C to quit
```

**Comment by Om-Thorat** [comment] 2023-07-29 16:47
and do you have spotify open with a song playing?

**Comment by qrwtey** [comment] 2023-07-29 16:48
ah, now I have spotify open:
```
Press CTRL+C to quit
The WebSocket transport is not available, you must install a WebSocket server that is compatible with your async mode to enable it. See the documentation for details. (further occurrences of this error will be logged with level INFO)
127.0.0.1 - - [29/Jul/2023 18:47:51] "GET /socket.io/?EIO=4&transport=polling&t=OcYZ9mw HTTP/1.1" 200 -
127.0.0.1 - - [29/Jul/2023 18:47:51] "POST /socket.io/?EIO=4&transport=polling&t=OcYZ9nz&sid=RXSNfQmY6D_oVgRKAAAA HTTP/1.1" 200 -
127.0.0.1 - - [29/Jul/2023 18:47:51] "GET /socket.io/?EIO=4&transport=polling&t=OcYZ9nz.0&sid=RXSNfQmY6D_oVgRKAAAA HTTP/1.1" 200 -
Bob Wins This Episode
127.0.0.1 - - [29/Jul/2023 18:47:51] "POST /socket.io/?EIO=4&transport=polling&t=OcYZ9oP.0&sid=RXSNfQmY6D_oVgRKAAAA HTTP/1.1" 200 -
```

**Comment by Om-Thorat** [comment] 2023-07-29 16:50
![image](https://github.com/Om-Thorat/Term-Spotify/assets/76207818/74f8bd2a-ea62-4b00-bbbc-2523a1e2670d)

expected behaviour it print the song that is playing currently,
you can also type in commands like PlayPause,
and it should pause the song.

![image](https://github.com/Om-Thorat/Term-Spotify/assets/76207818/833984e2-d1cb-4f97-83f9-648dbfefdbd6)

**Comment by Om-Thorat** [comment] 2023-07-29 16:52
> ah, now I have spotify open:
> 
> ```
> Press CTRL+C to quit
> The WebSocket transport is not available, you must install a WebSocket server that is compatible with your async mode to enable it. See the documentation for details. (further occurrences of this error will be logged with level INFO)
> 127.0.0.1 - - [29/Jul/2023 18:47:51] "GET /socket.io/?EIO=4&transport=polling&t=OcYZ9mw HTTP/1.1" 200 -
> 127.0.0.1 - - [29/Jul/2023 18:47:51] "POST /socket.io/?EIO=4&transport=polling&t=OcYZ9nz&sid=RXSNfQmY6D_oVgRKAAAA HTTP/1.1" 200 -
> 127.0.0.1 - - [29/Jul/2023 18:47:51] "GET /socket.io/?EIO=4&transport=polling&t=OcYZ9nz.0&sid=RXSNfQmY6D_oVgRKAAAA HTTP/1.1" 200 -
> Bob Wins This Episode
> 127.0.0.1 - - [29/Jul/2023 18:47:51] "POST /socket.io/?EIO=4&transport=polling&t=OcYZ9oP.0&sid=RXSNfQmY6D_oVgRKAAAA HTTP/1.1" 200 -
> ```

WELL that's working it's weird you are getting logs the script is defined to not log anything but that's working you can try `python3 app.py` now i guess

**Comment by qrwtey** [comment] 2023-07-29 16:58
That's pretty cool!
\- The same 2 or 3 errors using python3 app.py.
Thanks for the help so far, though the reason I was interested was because I was curious when I found it in the spicetify marketplace.
So it doesn't really matter if I get it working at all. But if you need someone to test this again I'm up for it 🙂
Gotta go, have a nice weekend.

**Comment by Om-Thorat** [comment] 2023-07-29 17:04
(oops sorry)

Thanks for having this amount of patience truly 😅. I'll let you know if i can replicate your problem with someone else.

**Comment by Om-Thorat** [comment] 2023-10-12 21:43
Cannot repro, Closing for now.

**Closed as completed by Om-Thorat** 2023-10-12 21:43 UTC

**Comment by loumox85** [comment] 2024-11-10 18:48
I have this issue : (plublished in the only current already opened issue)

`PS C:\Users\louka\Downloads\Term-Spotify-main> python app.py
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ C:\Users\louka\Downloads\Term-Spotify-main\app.py:17 in update_song                                                  │
│                                                                                                                      │
│   14 │   │   self.set_interval(1 / 60, self.update_song)                                                             │
│   15 │                                                                                                               │
│   16 │   def update_song(self):                                                                                      │
│ ❱ 17 │   │   self.song = pl.getdata()                                                                                │
│   18 │                                                                                                               │
│   19 │   def watch_song(self):                                                                                       │
│   20 │   │   self.update(f"Now Playing {self.song}")                                                                 │
│                                                                                                                      │
│ ╭──────────── locals ────────────╮                                                                                   │
│ │ self = Nowplaying(id='status') │                                                                                   │
│ ╰────────────────────────────────╯                                                                                   │
│                                                                                                                      │
│ C:\Users\louka\Downloads\Term-Spotify-main\api.py:38 in getdata                                                      │
│                                                                                                                      │
│   35 │                                                                                                               │
│   36 │   def getdata(self):                                                                                          │
│   37 │   │   self.proc.stdin.write("getdata\n")                                                                      │
│ ❱ 38 │   │   self.proc.stdin.flush()                                                                                 │
│   39 │   │   return self.proc.stdout.readline()                                                                      │
│   40                                                                                                                 │
│   41 if __name__ == "__main__":                                                                                      │
│                                                                                                                      │
│ ╭───────────────────── locals ─────────────────────╮                                                                 │
│ │ self = <api.Player object at 0x000002259F01ACF0> │                                                                 │
│ ╰──────────────────────────────────────────────────╯                                                                 │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
OSError: [Errno 22] Invalid argument

NOTE: 1 of 2 errors shown. Run with textual run --dev to see all errors.
PS C:\Users\louka\Downloads\Term-Spotify-main>`

python server.py running and music playing in background with spicetify and the plugin on

**Comment by ghost** [comment] 2024-11-26 02:49
getting the same error

╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ C:\Users\lucam\OneDrive\Desktop\Term-Spotify\app.py:17 in update_song                                                │
│                                                                                                                      │
│   14 │   │   self.set_interval(1 / 60, self.update_song)                                                             │
│   15 │                                                                                                               │
│   16 │   def update_song(self):                                                                                      │
│ ❱ 17 │   │   self.song = pl.getdata()                                                                                │
│   18 │                                                                                                               │
│   19 │   def watch_song(self):                                                                                       │
│   20 │   │   self.update(f"Now Playing {self.song}")                                                                 │
│                                                                                                                      │
│ ╭──────────── locals ────────────╮                                                                                   │
│ │ self = Nowplaying(id='status') │                                                                                   │
│ ╰────────────────────────────────╯                                                                                   │
│                                                                                                                      │
│ C:\Users\lucam\OneDrive\Desktop\Term-Spotify\api.py:38 in getdata                                                    │
│                                                                                                                      │
│   35 │                                                                                                               │
│   36 │   def getdata(self):                                                                                          │
│   37 │   │   self.proc.stdin.write("getdata\n")                                                                      │
│ ❱ 38 │   │   self.proc.stdin.flush()                                                                                 │
│   39 │   │   return self.proc.stdout.readline()                                                                      │
│   40                                                                                                                 │
│   41 if __name__ == "__main__":                                                                                      │
│                                                                                                                      │
│ ╭───────────────────── locals ─────────────────────╮                                                                 │
│ │ self = <api.Player object at 0x000001F6923ABE00> │                                                                 │
│ ╰──────────────────────────────────────────────────╯                                                                 │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
OSError: [Errno 22] Invalid argument
